### PR TITLE
Ethernaut Submissions Session 1- learnmutiny

### PR DESCRIPTION
**Pull request by zionmelson**
Ethernaut 0 Hash: 0x749353538a6cbc01f3184b576a61f0249ef6d56d9e115c2f5e477cc260934b77

Ethernaut 1 Hash: 0x4eecf7b7c9c6602d6cfd8d9e73a1aaca894c3fb997dd46bcb9ec6b39d8275a36

### CODE REVIEW

**Comment by Robert-H-Leonard** [comment]
Which testnet are you using for the ctfs?

**Comment by zionmelson** [comment]
Sorry, Sepolia testnet. And my address is: 0x29820d0fe80e57260998e9f8d68fd633b9bc7348

**Comment by JdejesusIsaac** [comment]
Ethernaut 1 Hash: 0x6806cde4cf037a963e157035422c4565ed56f80b142151e5b8cdadd69f98be91

**Comment by nadirahdurr** [comment]
Network: Sepolia testnet
Address: 0x7BCF6EC184D9683e0aD4bFD5843a7113C757251D

Ethernaut 0 Hash: 0x49bC79d3c900098803f471A0D070e1a7B5185D2a

**Pull request merged**
